/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

export interface DeleteCategory$Params {
  id: string;
  'If-Match'?: string;
}

export function deleteCategory(
  http: HttpClient,
  rootUrl: string,
  params: DeleteCategory$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, deleteCategory.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('If-Match', params['If-Match'], {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    }),
  );
}

deleteCategory.PATH = '/api/categories/{id}';
