/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryResponse } from '../../models/category-response';

export interface ListCategories$Params {}

export function listCategories(
  http: HttpClient,
  rootUrl: string,
  params?: ListCategories$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<CategoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, listCategories.PATH, 'get');
  if (params) {
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CategoryResponse>>;
    }),
  );
}

listCategories.PATH = '/api/categories';
