/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryResponse } from '../../models/category-response';
import { UpdateCategoryRequest } from '../../models/update-category-request';

export interface UpdateCategory$Params {
  id: string;
  'If-Match'?: string;
  body: UpdateCategoryRequest;
}

export function updateCategory(
  http: HttpClient,
  rootUrl: string,
  params: UpdateCategory$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<CategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, updateCategory.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CategoryResponse>;
    }),
  );
}

updateCategory.PATH = '/api/categories/{id}';
