/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Para onde mover: exatamente um dos dois.
 */
export interface CardLocationRequest {
  /**
   * Para a raiz do quadro desta categoria.
   */
  categoryId?: string | null;

  /**
   * Para dentro do quadro deste cartão (assumindo a categoria dele).
   */
  parentId?: string | null;
}
