/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CardPropertiesDto } from '../models/card-properties-dto';
import { CardRef } from '../models/card-ref';
import { JsonElement } from '../models/json-element';
import { PositionDto } from '../models/position-dto';
import { SizeDto } from '../models/size-dto';
export interface CardResponse {
  ancestors?: Array<CardRef> | null;
  categoryId: string;
  childCount: number;
  color: string;
  content: null | JsonElement;
  createdAt: string;
  id: string;
  layer: number;
  parentId: string | null;
  position: PositionDto;
  properties: CardPropertiesDto;
  size: SizeDto;
  title: string;
  updatedAt: string;
  version: string;
}
