/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryResponse {
  createdAt: string;
  id: string;
  name: string;
  sortOrder: number;
  updatedAt: string;
  version: string;
}
