/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PositionDto } from '../models/position-dto';
export interface CreateCardRequest {
  /**
   * Gerado pelo cliente (UUID v7): repetir o pedido com o mesmo id não duplica o cartão.
   */
  id: string;

  /**
   * Onde o cartão aparece no quadro.
   */
  position: PositionDto;

  /**
   * Título: 1 a 200 caracteres.
   */
  title: string;
}
