/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateCategoryRequest {
  /**
   * Gerado pelo cliente (UUID v7): repetir o pedido com o mesmo id não duplica a categoria.
   */
  id: string;

  /**
   * Nome da aba: 1 a 100 caracteres, único entre as categorias do usuário.
   */
  name: string;
}
