/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Só os campos enviados são alterados (todos opcionais).
 */
export interface UpdateCategoryRequest {
  name?: string | null;
  sortOrder?: number | null;
}
