/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CardLocationRequest } from '../models/card-location-request';
import { CardPropertiesDto } from '../models/card-properties-dto';
import { JsonElement } from '../models/json-element';
import { PositionDto } from '../models/position-dto';
import { SizeDto } from '../models/size-dto';

/**
 * Só os campos enviados são alterados (todos opcionais).
 */
export interface UpdateCardRequest {
  /**
   * Cor livre, no formato #rrggbb.
   */
  color?: string | null;
  content?: null | JsonElement;
  location?: null | CardLocationRequest;
  position?: null | PositionDto;
  properties?: null | CardPropertiesDto;
  size?: null | SizeDto;
  title?: string | null;
}
