// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planner.Infrastructure.Persistence;

#nullable disable

namespace Planner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlannerDbContext))]
    [Migration("20261001071408_AddCardSize")]
    partial class AddCardSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Planner.Domain.Cards.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("#e5e7eb")
                        .HasColumnName("color");

                    b.Property<string>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Layer")
                        .HasColumnType("integer")
                        .HasColumnName("layer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Position", "Planner.Domain.Cards.Card.Position#Position", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("X")
                                .HasColumnType("double precision")
                                .HasColumnName("position_x");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision")
                                .HasColumnName("position_y");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Size", "Planner.Domain.Cards.Card.Size#Size", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Height")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("double precision")
                                .HasDefaultValue(64.0)
                                .HasColumnName("height");

                            b1.Property<double>("Width")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("double precision")
                                .HasDefaultValue(208.0)
                                .HasColumnName("width");
                        });

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.HasIndex("CategoryId", "ParentId")
                        .HasDatabaseName("ix_cards_category_id_parent_id");

                    b.HasIndex("ParentId", "CategoryId")
                        .HasDatabaseName("ix_cards_parent_id_category_id");

                    b.ToTable("cards", null, t =>
                        {
                            t.HasCheckConstraint("ck_cards_color", "color ~ '^#[0-9a-f]{6}$'");

                            t.HasCheckConstraint("ck_cards_content", "content IS NULL OR jsonb_typeof(content) = 'object'");

                            t.HasCheckConstraint("ck_cards_properties", "jsonb_typeof(properties) = 'object'");

                            t.HasCheckConstraint("ck_cards_size", "width BETWEEN 120 AND 1200 AND height BETWEEN 48 AND 900");

                            t.HasCheckConstraint("ck_cards_title", "title = btrim(title) AND length(title) BETWEEN 1 AND 200");
                        });
                });

            modelBuilder.Entity("Planner.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_name", "name = btrim(name) AND length(name) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Planner.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_email", "length(email) <= 254");

                            t.HasCheckConstraint("ck_users_name", "name = btrim(name) AND length(name) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Planner.Domain.Cards.Card", b =>
                {
                    b.HasOne("Planner.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cards_categories_category_id");

                    b.HasOne("Planner.Domain.Cards.Card", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_cards_cards_parent_id");
                });

            modelBuilder.Entity("Planner.Domain.Categories.Category", b =>
                {
                    b.HasOne("Planner.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
