/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CardResponse } from '../../models/card-response';
import { CreateCardRequest } from '../../models/create-card-request';

export interface CreateRootCard$Params {
  categoryId: string;
  body: CreateCardRequest;
}

export function createRootCard(
  http: HttpClient,
  rootUrl: string,
  params: CreateRootCard$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<CardResponse>> {
  const rb = new RequestBuilder(rootUrl, createRootCard.PATH, 'post');
  if (params) {
    rb.path('categoryId', params.categoryId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CardResponse>;
    }),
  );
}

createRootCard.PATH = '/api/categories/{categoryId}/cards';
