/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CardResponse } from '../../models/card-response';

export interface ListChildCards$Params {
  id: string;
}

export function listChildCards(
  http: HttpClient,
  rootUrl: string,
  params: ListChildCards$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<Array<CardResponse>>> {
  const rb = new RequestBuilder(rootUrl, listChildCards.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CardResponse>>;
    }),
  );
}

listChildCards.PATH = '/api/cards/{id}/children';
