/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CardResponse } from '../../models/card-response';
import { UpdateCardRequest } from '../../models/update-card-request';

export interface UpdateCard$Params {
  id: string;
  'If-Match'?: string;
  body: UpdateCardRequest;
}

export function updateCard(
  http: HttpClient,
  rootUrl: string,
  params: UpdateCard$Params,
  context?: HttpContext,
): Observable<StrictHttpResponse<CardResponse>> {
  const rb = new RequestBuilder(rootUrl, updateCard.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('If-Match', params['If-Match'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(rb.build({ responseType: 'json', accept: 'application/json', context })).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CardResponse>;
    }),
  );
}

updateCard.PATH = '/api/cards/{id}';
