<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <!-- Só para as ferramentas de migration; não vai para o app publicado. -->
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Planner.Application\Planner.Application.csproj" />
    <ProjectReference Include="..\Planner.Domain\Planner.Domain.csproj" />
  </ItemGroup>

</Project>
